import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WrapperBackground } from "@/components/ui/WrapperBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gothamBlack = localFont({
  src: "../../public/fonts/Gotham-Black.woff2",
  variable: "--font-gotham-black",
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gothamBlack.variable}`}>
        <WrapperBackground>
          {children}
        </WrapperBackground>
      </body>
    </html>
  );
}
