import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WrapperBackground } from "@/components/ui/WrapperBackground";
import { ThemeProvider } from "@/lib/theme-provider";
import { ThemeToggle } from "@/components/ui/ThemeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gothamBlack = localFont({
  src: "../../public/fonts/Gotham-Black.woff2",
  variable: "--font-gotham-black",
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${gothamBlack.variable}`}>
        <ThemeProvider defaultTheme="system" storageKey="sky-connect-theme">
          <WrapperBackground>
            <div className="absolute top-4 right-4 z-20">
              <ThemeToggle />
            </div>
            {children}
          </WrapperBackground>
        </ThemeProvider>
      </body>
    </html>
  );
}
